version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8081:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "8282:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
